name: ros2-base-humble
version: '2.2.0'
summary: ROS 2 Humble base snap for ctrlX CORE
description: |
  Provides ROS 2 Humble for ROS 2 applications running on a for ctrlX CORE.

base: core22
grade: stable
confinement: strict

apps:
  server:
    command: usr/bin/runner
    plugs:
      - ros-base
      - network
      - network-bind
      - shmem-plug
    slots: [shmem-slot] 
    daemon: simple
    passthrough:
      restart-condition: always
      restart-delay: 10s

parts:
  interfaces:
    plugin: dump
    source: install
    override-build: |
        snapcraftctl build

  wrapper-scripts:
    plugin: dump
    source: wrapper/
    organize:
      ./runner.sh : usr/bin/runner
  ros-base:
    plugin: colcon
    build-packages: [make, gcc, g++]
    stage-packages: [
      software-properties-common,
      ros-humble-ros-base,
      ros-humble-rosbridge-server,
      python3-argcomplete,
      python3-netifaces,
      ca-certificates
    ]
    build-environment:
      - ROS_VERSION: '2'
      - ROS_DISTRO: humble
  
  datalayer:
    plugin: nil
    stage-packages:
      - libzmq5
      - ctrlx-datalayer

  helper: 
    plugin: python
    build-environment:
      - PYTHONPATH: "$SNAPCRAFT_PART_INSTALL/usr/lib/python3/dist-packages"
    stage-packages:
      - python3-wheel
    python-packages: 
      - ctrlx-datalayer
      - empy
      - numpy
      - rosdep 
      - netifaces
      - pymongo
      - Pillow
      - tornado
      - rosdistro
      - colcon-core
      - lark

slots:
  ros-base:
    interface: content
    content: executables
    read: [/]

  shmem-slot:
    interface: shared-memory
    write: ['*'] # paths are relative to /dev/shm
    private: false 
plugs:
  shmem-plug:
    interface: shared-memory
    shared-memory: shmem-slot
    private: false