name: ros2-moveit-mtc
version: '2.2.0'
summary: Snap with MoveIt2, MoveIt task constructor and ros2_control example
description: |
  It runs a fake Panda robot HW, the corresponding robot controllers and the MTC planning. Visualization happens in desktop computer.

base: core22
grade: stable
confinement: strict

parts:
  ros-app:
    plugin: dump
    source: ./install
    # organize:
    #  '*': ros-app/    
    stage-packages:
      - ros-humble-moveit
      - ros-humble-xacro
      - ros-humble-ros2-control
      - ros-humble-ros2-controllers 
      - ros-humble-gripper-controllers
      - ros-humble-moveit-resources-panda-moveit-config
      - ros-humble-moveit-resources-panda-description
      - libzmq5 # related with dataLayer (not used here)
      - ctrlx-datalayer # related with dataLayer (not used here)
    override-build: |
        snapcraftctl build
                
  wrapper-scripts:
    plugin: dump
    source: ./wrapper
    organize:
      '*' : usr/bin/

apps:
  initALL:
    command: usr/bin/run-initALL.sh
    plugs:
      - ros-base
      - network
      - network-bind
    # daemon: simple
    # passthrough:
      # restart-condition: always
      # restart-delay: 10s
  task:
    command: usr/bin/run-task.sh
    plugs:
      - ros-base
      - network
      - network-bind
    # daemon: simple
    # passthrough:
      # restart-condition: always
      # restart-delay: 10s   
    

plugs:
  ros-base:
    interface: content
    content: executables
    target: $SNAP/rosruntime
    
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer
