name: ros2-scara-publisher-cpp
version: '2.2.0'
summary: Snap with ROS 2 node that publish the actual joint state of the SCARA robot.
description: Snap with ROS 2 node that publish the actual joint state of the SCARA robot.
base: core22
grade: stable
confinement: strict

parts:
  ros-app:
    plugin: dump
    source: install
    stage-packages:
      - libzmq5
      - ctrlx-datalayer
    override-build: |
        snapcraftctl build

  wrapper-scripts:
    plugin: dump
    source: wrapper/
    organize:
      ./run-scara-publisher.sh : usr/bin/run-scara-publisher

apps:
  listener:
    command: usr/bin/run-scara-publisher
    plugs:
      - ros-base
      - network
      - network-bind
    daemon: simple
    passthrough:
      restart-condition: always
      restart-delay: 10s

plugs:
  ros-base:
    interface: content
    content: executables
    target: $SNAP/rosruntime
    
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer
