name: ros2-listener-shm-dl
version: '2.2.0'
summary: Snap with ROS 2 listener that writes to Datalayer using shared memory
description: |
  A ROS 2 listener which receives ROS 2 messages on topic '/test_vector3' and writres to Datalayer using shared memory on 'ros2/rt/ROS_input. Spinning at 200 Hz.

base: core22
grade: stable
confinement: strict

parts:
  ros-app:
    plugin: dump
    source: install
    stage-packages:
      - libzmq5
      - ctrlx-datalayer
    override-build: |
        snapcraftctl build

  wrapper-scripts:
    plugin: dump
    source: wrapper/
    organize:
      ./run-listener.sh : usr/bin/run-listener

apps:
  listener:
    command: usr/bin/run-listener
    plugs:
      - ros-base
      - network
      - network-bind
      - datalayer
      - datalayer-shm
    daemon: simple
    passthrough:
      restart-condition: always
      restart-delay: 10s

plugs:
  ros-base:
    interface: content
    content: executables
    target: $SNAP/rosruntime
    
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer
    
  datalayer-shm:
    interface: shared-memory
    shared-memory: datalayer-shm

