name: ros2-io-manager-input-cpp
version: '2.2.0'
summary: ROS 2 node mapping ctrlX IO-input to a ROS2 topic.
description: Snap with ROS 2 node that reads an IO-input and publishes them to a ROS2 topic.
base: core22
grade: stable
confinement: strict

parts:
  ros-app:
    plugin: dump
    source: install
    stage-packages:
      - libzmq5
      - ctrlx-datalayer
    override-build: |
        snapcraftctl build

  wrapper-scripts:
    plugin: dump
    source: wrapper/
    organize:
      ./io-manager-input.sh : usr/bin/io-manager-input

apps:
  listener:
    command: usr/bin/io-manager-input
    plugs:
      - ros-base
      - network
      - network-bind
    daemon: simple
    passthrough:
      restart-condition: always
      restart-delay: 10s

plugs:
  ros-base:
    interface: content
    content: executables
    target: $SNAP/rosruntime
    
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer
