name: ros2-talker-shm-dl
version: '2.2.0'
summary: Snap with ROS 2 talker that reads from shared memory in Datalayer 
description: |
  A ROS 2 talker which reads from shared memory in Datalayer on /plc/app/realtime_data/PLC_output and publishes the ROS2 topic '/PLC_output'. Spinning at 200Hz.

base: core22
grade: stable
confinement: strict

parts:
  ros-app:
    plugin: dump
    source: install
    stage-packages:
      - libzmq5
      - ctrlx-datalayer
    override-build: |
        snapcraftctl build

  wrapper-scripts:
    plugin: dump
    source: wrapper/
    organize:
      ./run-talker.sh : usr/bin/run-talker

apps:
  talker:
    command: usr/bin/run-talker
    plugs:
      - ros-base
      - network
      - network-bind
      - datalayer
      - datalayer-shm
    daemon: simple
    passthrough:
      restart-condition: always
      restart-delay: 10s

plugs:
  ros-base:
    interface: content
    content: executables
    target: $SNAP/rosruntime
    
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer
    
  datalayer-shm:
    interface: shared-memory
    shared-memory: datalayer-shm

